security:
    enable_authenticator_manager: true

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            json_login:
                check_path: /login
                username_path: email
                password_path: password
            logout:
                path: /logout
                invalidate_session: true

        admin:
            pattern: ^/admin
            provider: app_user_provider
            json_login:
                check_path: /admin/login
                username_path: email
                password_path: password
            logout:
                path: /admin/logout
                invalidate_session: true

    password_hashers:
        App\Entity\User:
            algorithm: auto

    access_control:
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }
        - { path: ^/api/check-auth, roles: PUBLIC_ACCESS }
        - { path: ^/transactions, roles: ROLE_USER }
        - { path: ^/account, roles: ROLE_USER }
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: PUBLIC_ACCESS }
        - { path: ^/about, roles: PUBLIC_ACCESS }
        - { path: ^/contact, roles: PUBLIC_ACCESS }
        - { path: ^/blog, roles: PUBLIC_ACCESS }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
