controllers:
    resource: ../src/Controller/
    type: attribute
api_register:
    path: /api/register
    controller: App\Controller\AccountController::register
    methods: [POST]

api_login:
    path: /api/login
    controller: App\Controller\AccountController::login
    methods: [POST]

api_logout:
    path: /api/logout
    controller: App\Controller\AccountController::logout
    methods: [POST]

api_check_auth:
    path: /api/check-auth
    methods: [GET]
    controller: App\Controller\AuthController::checkAuth
account:
    path: /account
    controller: App\Controller\AccountController::account
    methods: [GET, POST]