controllers:
    resource: ../src/Controller/
    type: attribute

api_register:
    path: /register
    controller: App\Controller\AccountController::register
    methods: [POST]

api_login:
    path: /login
    controller: App\Controller\AccountController::login
    methods: [POST]

api_logout:
    path: /logout
    controller: App\Controller\AccountController::logout
    methods: [POST]

api_check_auth:
    path: /api/check-auth
    controller: App\Controller\AuthController::checkAuth
    methods: [GET]

account:
    path: /account
    controller: App\Controller\AccountController::account
    methods: [GET, POST]

category_index:
    path: /categories
    controller: App\Controller\CategoryController::index
    methods: [GET]

category_create:
    path: /categories
    controller: App\Controller\CategoryController::create
    methods: [POST]

category_show:
    path: /categories/{id}
    controller: App\Controller\CategoryController::show
    methods: [GET]

category_update:
    path: /categories/{id}
    controller: App\Controller\CategoryController::update
    methods: [PUT]

category_delete:
    path: /categories/{id}
    controller: App\Controller\CategoryController::delete
    methods: [DELETE]

expense_index:
    path: /expenses
    controller: App\Controller\ExpenseController::index
    methods: [GET]

expense_create:
    path: /expenses
    controller: App\Controller\ExpenseController::create
    methods: [POST]

expense_show:
    path: /expenses/{id}
    controller: App\Controller\ExpenseController::show
    methods: [GET]

expense_update:
    path: /expenses/{id}
    controller: App\Controller\ExpenseController::update
    methods: [PUT]

expense_delete:
    path: /expenses/{id}
    controller: App\Controller\ExpenseController::delete
    methods: [DELETE]

income_index:
    path: /incomes
    controller: App\Controller\IncomeController::index
    methods: [GET]

income_create:
    path: /incomes
    controller: App\Controller\IncomeController::create
    methods: [POST]

income_show:
    path: /incomes/{id}
    controller: App\Controller\IncomeController::show
    methods: [GET]

income_update:
    path: /incomes/{id}
    controller: App\Controller\IncomeController::update
    methods: [PUT]

income_delete:
    path: /incomes/{id}
    controller: App\Controller\IncomeController::delete
    methods: [DELETE]

comment_create:
    path: /comments
    controller: App\Controller\CommentController::create
    methods: [POST]

comment_index:
    path: /comments/{postId}
    controller: App\Controller\CommentController::index
    methods: [GET]

comment_delete:
    path: /comments/{id}
    controller: App\Controller\CommentController::delete
    methods: [DELETE]

blog_index:
    path: /blog
    controller: App\Controller\BlogController::index
    methods: [GET]

blog_new:
    path: /blog/new
    controller: App\Controller\BlogController::new
    methods: [POST]

blog_show:
    path: /blog/{id}
    controller: App\Controller\BlogController::show
    methods: [GET]

blog_edit:
    path: /blog/{id}/edit
    controller: App\Controller\BlogController::edit
    methods: [POST]

blog_delete:
    path: /blog/{id}
    controller: App\Controller\BlogController::delete
    methods: [DELETE]
