controllers:
    resource: ../src/Controller/
    type: attribute
api_register:
    path: /api/register
    controller: App\Controller\AccountController::register
    methods: POST

api_login:
    path: /api/login
    controller: App\Controller\AccountController::login
    methods: POST
api_check-auth:
    path: /api/check-auth
    controller: App\Controller\AccountController::check
    methods: GET