controllers:
    resource: ../src/Controller/
    type: attribute

api_register:
    path: /register
    controller: App\Controller\AccountController::register
    methods: [POST]

api_login:
    path: /login
    controller: App\Controller\AccountController::login
    methods: [POST]

api_logout:
    path: /logout
    controller: App\Controller\AccountController::logout
    methods: [POST]

api_check_auth:
    path: /api/check-auth
    controller: App\Controller\AuthController::checkAuth
    methods: [GET]

account:
    path: /account
    controller: App\Controller\AccountController::account
    methods: [GET, POST]

category_index:
    path: /categories
    controller: App\Controller\CategoryController::index
    methods: [GET]

category_create:
    path: /categories
    controller: App\Controller\CategoryController::create
    methods: [POST]

category_show:
    path: /categories/{id}
    controller: App\Controller\CategoryController::show
    methods: [GET]

category_update:
    path: /categories/{id}
    controller: App\Controller\CategoryController::update
    methods: [PUT]

category_delete:
    path: /categories/{id}
    controller: App\Controller\CategoryController::delete
    methods: [DELETE]

expense_index:
    path: /expenses
    controller: App\Controller\ExpenseController::index
    methods: [GET]

expense_create:
    path: /expenses
    controller: App\Controller\ExpenseController::create
    methods: [POST]

expense_show:
    path: /expenses/{id}
    controller: App\Controller\ExpenseController::show
    methods: [GET]

expense_update:
    path: /expenses/{id}
    controller: App\Controller\ExpenseController::update
    methods: [PUT]

expense_delete:
    path: /expenses/{id}
    controller: App\Controller\ExpenseController::delete
    methods: [DELETE]

income_index:
    path: /incomes
    controller: App\Controller\IncomeController::index
    methods: [GET]

income_create:
    path: /incomes
    controller: App\Controller\IncomeController::create
    methods: [POST]

income_show:
    path: /incomes/{id}
    controller: App\Controller\IncomeController::show
    methods: [GET]

income_update:
    path: /incomes/{id}
    controller: App\Controller\IncomeController::update
    methods: [PUT]

income_delete:
    path: /incomes/{id}
    controller: App\Controller\IncomeController::delete
    methods: [DELETE]

blog_posts:
    path: /api/blog-posts
    controller: App\Controller\BlogController::getBlogPosts
    methods: GET

blog_post:
    path: /api/blog-posts/{id}
    controller: App\Controller\BlogController::getBlogPost
    methods: GET

create_blog_post:
    path: /api/blog-posts
    controller: App\Controller\BlogController::createBlogPost
    methods: POST

update_blog_post:
    path: /api/blog-posts/{id}
    controller: App\Controller\BlogController::updateBlogPost
    methods: PUT

delete_blog_post:
    path: /api/blog-posts/{id}
    controller: App\Controller\BlogController::deleteBlogPost
    methods: DELETE

get_comments:
    path: /api/blog-posts/{id}/comments
    controller: App\Controller\CommentController::getComments
    methods: GET

add_comment:
    path: /api/blog-posts/{id}/comments
    controller: App\Controller\CommentController::addComment
    methods: POST

admin_dashboard:
    path: /api/admin/dashboard
    controller: App\Controller\AdminController::dashboard
    methods: [GET]

admin_manage_users:
    path: /api/admin/users
    controller: App\Controller\AdminController::manageUsers
    methods: [GET]

admin_user_create:
    path: /api/admin/users/create
    controller: App\Controller\AdminController::createUser
    methods: [GET, POST]

admin_user_edit:
    path: /api/admin/users/{id}/edit
    controller: App\Controller\AdminController::editUser
    methods: [GET, POST]

admin_user_delete:
    path: /api/admin/users/{id}/delete
    controller: App\Controller\AdminController::deleteUser
    methods: [POST]

admin_manage_blogs:
    path: /api/admin/blogs
    controller: App\Controller\AdminController::manageBlogs
    methods: [GET]

admin_blog_edit:
    path: /api/admin/blogs/{id}/edit
    controller: App\Controller\AdminController::editBlogPost
    methods: [GET, POST]

admin_blog_delete:
    path: /api/admin/blogs/{id}/delete
    controller: App\Controller\AdminController::deleteBlogPost
    methods: [POST]

admin_manage_comments:
    path: /api/admin/comments
    controller: App\Controller\AdminController::manageComments
    methods: [GET]

admin_comment_edit:
    path: /api/admin/comments/{id}/edit
    controller: App\Controller\AdminController::editComment
    methods: [GET, POST]

admin_comment_delete:
    path: /api/admin/comments/{id}/delete
    controller: App\Controller\AdminController::deleteComment
    methods: [POST]

admin_login:
    path: /api/admin/login
    controller: App\Controller\AdminController::login
    methods: [GET, POST]

admin_logout:
    path: /api/admin/logout
    controller: App\Controller\AdminController::logout
    methods: [GET, POST]

react_routing:
    path: /{reactRouting}
    controller: App\Controller\DefaultController::index
    requirements:
        reactRouting: .*
